[env]
TERM = "xterm-256color"

[window]
dimensions = { lines = 40, columns = 140 }

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Normal"

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Italic"
# style = "Bold"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[general]
#

import = [
   "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
